spring.application.name=TransactionApplication
spring.jackson.property-naming-strategy=SNAKE_CASE

# H2 in-memory (default profile)
spring.datasource.url=jdbc:h2:mem:transactionsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.validate-migration-naming=true

# H2 Console (useful during dev)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console