CREATE TABLE accounts (
  account_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_number VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE operation_types (
  operation_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description       VARCHAR(50) NOT NULL
);

CREATE TABLE transactions (
  transaction_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  account_id        BIGINT                   NOT NULL,
  operation_type_id BIGINT                   NOT NULL,
  amount            DECIMAL(19, 2)           NOT NULL,
  event_date        TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT pk_transactions
      PRIMARY KEY (transaction_id),

  CONSTRAINT fk_transaction_account
      FOREIGN KEY (account_id)
          REFERENCES accounts (account_id),

  CONSTRAINT fk_transaction_operation_type
      FOREIGN KEY (operation_type_id)
          REFERENCES operation_types (operation_type_id),

  CONSTRAINT chk_amount_not_zero
      CHECK (amount <> 0)
);

CREATE INDEX idx_transactions_account_id
    ON transactions (account_id);